name: vencopy
channels:
  - conda-forge
  - defaults
dependencies:
  - click
  - jupyterlab
  - matplotlib
  - openpyxl
  - pandas
  - python=3.9
  - pyyaml
  - seaborn
  - sphinx
  - sphinx_rtd_theme
  - yaml
