#-*- coding:utf-8 -*-

# __version__ = '0.0.8'
# __maintainer__ = 'Niklas Wulff 2019-02-12'
# __email__ = 'Niklas.Wulff@dlr.de'
# __birthdate__ = '2019-02-12'
# __status__ = 'dev'  # options are: dev, test, prod

# This config holds all relative paths and filenames for VENCO
numberOfHours: 24

linksRelative:
    input: ./inputData/
    plots: ./output/plots/
    plotsMiDAna: ./output/plotsMIDAna/
    plotsDCMob: ./output/plots/plotsDC/mob/
    plotsDCFlex: ./output/plots/plotsDC/flex/
    resultsDaily: ./output/dailyTimeseries/
    resultsDailyDC: ./output/dailyTimeseries/dcAna/
    resultsAnnual: ./output/annualTimeseries/
    scripts: ./scripts/
    config: ./config/
    outputConfig: ./config/outputConfigREMix.yaml
    sesData: ./output/sesAnalysis/data/
    sesPlots: ./output/sesAnalysis/plots/

# During first configuration, optionally fill in absolute links on your system e.g. if you want to have post processed
# output written to an energy system model input folder
linksAbsolute:
    folderMiD2017_B1: C:/Users/wulf_ni/Documents/11 Data/Transport data/Germany/MiD/2017/proprietary/B1/CSV
    MiD17: C:/Users/wulf_ni/Documents/11 Data/Transport data/Germany/MiD/2017/proprietary/B2/STATA
    MiD08: C:/Users/wulf_ni/Documents/11 Data/Transport data/Germany/MiD/2008/MiD 2008_DVD/Daten/STATA/STATA_Public Use File

files:
    inputDataScalars: VencoPy_scalarInputSES.xlsx
#    inputDataDriveProfiles: inputProfiles_Drive_MiD17_woWeights.csv
#    inputDataPlugProfiles: inputProfiles_Plug_MiD17_woWeights.csv
    MiD17:
        householdsDataRaw: MiD2017_Regional_Haushalte.csv
        personsDataRaw: MiD2017_Regional_Personen.csv
        tripsDataRaw: MiD2017_Regional_Wege.dta
        purposesProcessed: inputProfiles_Purpose  # inputProfiles_Purpose_runTest_MiD17.csv
        inputDataDriveProfiles: inputProfiles_Drive  # inputProfiles_Drive_runTest_MiD17.csv
        inputDataPlugProfiles: inputProfiles_Plug  # inputProfiles_Plug_runTest_MiD17.csv
    MiD08:
        householdsDataRaw: MiD2008_PUF_Haushalte.dta
        personDataRaw: MiD2008_PUF_Personen.dta
        tripsDataRaw: MiD2008_PUF_Wege.dta
        tripsProcessedOld: MiD_procCS_caseID-weekday-weight-activity.xlsx
        purposesProcessedOld: MiD_procCS_caseID-weekday-weight-activity.xlsx
        purposesProcessed: inputProfiles_Purpose  # inputProfiles_Purpose_runTest_MiD08.csv
        inputDataDriveProfiles: inputProfiles_Drive  # inputProfiles_Drive_runTest_MiD08.csv
        inputDataPlugProfiles: inputProfiles_Plug  # inputProfiles_Plug_runTest_MiD08.csv
#        inputDataDriveProfiles: inputProfiles_Drive_MiD08.csv
#        inputDataPlugProfiles: inputProfiles_Plug_MiD08.csv

midVariables:
    dataset: ['MiD08', 'MiD17']
    isMIVDriver: ['pkw_f','W_VM_G']
    hhPersonID: ['pid','HP_ID_Reg']
    tripID: ['wid', 'W_ID']
    tripWeight: ['w_gew','W_GEW']
    tripScaleFactor: ['NA', 'W_HOCH']
    tripStartClock: ['st_time', 'W_SZ']
    tripEndClock: ['en_time', 'W_AZ']
    tripPurpose: ['w04', 'zweck']
    tripDistance: ['wegkm_k', 'wegkm']
    tripStartYear: ['stich_j', 'ST_JAHR']
    tripStartMonth: ['stich_m', 'ST_MONAT']
    tripStartWeek: ['stichwo', 'ST_WOCHE']
    tripStartWeekday: ['stichtag', 'ST_WOTAG']
    tripStartHour: ['st_std', 'W_SZS']
    tripStartMinute: ['st_min', 'W_SZM']
    tripEndHour: ['en_std', 'W_AZS']
    tripEndMinute: ['en_min', 'W_AZM']
    tripEndNextDay: ['en_dat', 'W_FOLGETAG']
    tripIsIntermodal: ['NA', 'weg_intermod']

inputDTypes:
    isMIVDriver: 'b'
    tripID: 'i'
    tripWeight: 'f'
    tripStartClock: 'f'
    tripEndClock: 'f'
    tripPurpose: 'i'
    tripDistance: 'f'
    tripStartYear: 'i'
    tripStartMonth: 'i'
    tripStartWeek: 'i'
    tripStartWeekday: 'i'
    tripStartHour: 'i'
    tripStartMinute: 'i'
    tripEndHour: 'i'
    tripEndMinute: 'i'
    tripEndNextDay: 'b'

labels:
    runLabel: baseDC
    technologyLabel: BEV-S
    outputFileName: VencoPy_MR1_alpha1_batCap40_cons15
    strAdd: 11kW_SAM

postprocessing:
    hoursClone: 8760

midTripPurposeReplacements:
    1: 'WORK'  # Erreichen des Arbeitsplatzes
    2: 'WORK'  # dienstlich/gesch채ftlich
    3: 'SCHOOL'  # Erreichen der Ausbildungsst채tte/Schule
    4: 'SHOPPING'  # Einkauf
    5: 'SHOPPING'  # private Erledigung
    6: 'LEISURE'  # Bringen/Holen/Begleiten von Personen
    7: 'LEISURE'  # Freizeitaktivit채t
    8: 'HOME'  # nach Hause
    9: 'HOME'  # R체ckweg vom vorherigen Weg
    10: 'OTHER'  # anderer Zweck
    99: 'NA'  # keine Angabe

chargingInfrastructureDistributions:  # Probabilities given for each location aka trip purpose
    'DRIVING': 'FALSCH'
    'HOME': 'WAHR'
    'WORK': 'FALSCH'
    'SCHOOL': 'FALSCH'
    'SHOPPING': 'FALSCH'
    'LEISURE': 'FALSCH'
    'OTHER': 'FALSCH'
    'NA': 'FALSCH'

chargingInfrastructureDistributionsSchimmy:  # Identifiers from the evaluation of MID08 by Christoph Schimeczek
    'driving': 'FALSCH'
    'home': 'WAHR'
    'work': 'FALSCH'
    'school': 'FALSCH'
    'shop': 'FALSCH'
    'private': 'FALSCH'
    'recreation': 'FALSCH'
    'other': 'FALSCH'
    'n/a': 'FALSCH'
    nan: 'FALSCH'

plotConfig:
    show: True
    save: True
    plotRCParameters:
        font.family: sans-serif
        font.weight: normal
        font.size: 14
        axes.labelsize: 18
        axes.labelpad: 8.0