#-*- coding:utf-8 -*-

# __version__ = '0.0.8'
# __maintainer__ = 'Niklas Wulff 2019-02-12'
# __email__ = 'Niklas.Wulff@dlr.de'
# __birthdate__ = '2019-02-12'
# __status__ = 'dev'  # options are: dev, test, prod

# This config holds all relative paths and filenames for VENCO

linksRelative:
    input: ./inputData/
    plots: ./output/plots/
    resultsDaily: ./output/dailyTimeseries/
    resultsAnnual: ./output/annualTimeseries/
    scripts: ./scripts/
    config: ./config/
    outputConfig: ./config/outputConfigREMix.yaml

# During first configuration, optionally fill in absolute links on your system e.g. if you want to have post processed
# output written to an energy system model input folder
linksAbsolute:
    folderMiD2017: C:/Users/wulf_ni/Documents/11 Data/Transport data/Germany/MiD/2017/proprietary/CSV
    folderMiD2008: C:/Users/wulf_ni/Documents/11 Data/Transport data/Germany/MiD/2008/MiD 2008_DVD/Daten/STATA/STATA_Public Use File

files:
    inputDataScalars: VencoPy_scalarInput.xlsx
    inputDataDriveProfiles: inputProfiles_Drive.csv
    inputDataPlugProfiles: inputProfiles_Plug.csv
    MiD2017households: MiD2017_Regional_Haushalte.csv
    MiD2017persons: MiD2017_Regional_Personen.csv
    MiD2017trips: MiD2017_Regional_Wege.csv

labels:
    technologyLabel: BEV-S
    outputFileName: VencoPy_MR1_alpha1_batCap40_cons15

postprocessing:
    hoursClone: 8760