#-*- coding:utf-8 -*-

# __version__ = '0.0.9'
# __maintainer__ = 'Niklas Wulff 2019-02-12'
# __contributors__ = 'Fabia Miorelli, Parth Butte'
# __email__ = 'Niklas.Wulff@dlr.de'
# __birthdate__ = '2019-02-12'
# __status__ = 'dev'  # options are: dev, test, prod

# This config holds all relative paths and filenames for VencoPy

pathRelative:
    input: ./inputData/
    plots: ./output/plots/
    dataOutput: ./output/data/
    scripts: ./scripts/
    config: ./config/


numberOfHours: 24

files:
    inputDataScalars: VencoPy_scalarInput.xlsx
#    inputDataDriveProfiles: inputProfiles_Drive_MiD17_woWeights.csv
#    inputDataPlugProfiles: inputProfiles_Plug_MiD17_woWeights.csv
    MiD17:
        enryptedZipFileB1: B1_Standard-DatensatzpaketEncrypted.zip
        enryptedZipFileB2: B2_Regional-DatensatzpaketEncrypted.zip
        tripDataZipFileRaw: CSV/MiD2017_Regional_Wege.csv
        householdsDataRaw: MiD2017_Regional_Haushalte.csv
        personsDataRaw: MiD2017_Regional_Personen.csv
        tripsDataRaw: MiD2017_Regional_Wege.dta
        purposesProcessed: inputProfiles_Purpose  # inputProfiles_Purpose_runTest_MiD17.csv
        inputDataDriveProfiles: inputProfiles_Drive  # inputProfiles_Drive_runTest_MiD17.csv
        inputDataPlugProfiles: inputProfiles_Plug  # inputProfiles_Plug_runTest_MiD17.csv
        vencoPyOutput: vencoPyOutput
        flexPlotName: flexProfileComparison
    MiD08:
        householdsDataRaw: MiD2008_PUF_Haushalte.dta
        personDataRaw: MiD2008_PUF_Personen.dta
        tripsDataRaw: MiD2008_PUF_Wege.dta
        tripsProcessedOld: MiD_procCS_caseID-weekday-weight-activity.xlsx
        purposesProcessedOld: MiD_procCS_caseID-weekday-weight-activity.xlsx
        purposesProcessed: inputProfiles_Purpose  # inputProfiles_Purpose_runTest_MiD08.csv
        inputDataDriveProfiles: inputProfiles_Drive  # inputProfiles_Drive_runTest_MiD08.csv
        inputDataPlugProfiles: inputProfiles_Plug  # inputProfiles_Plug_runTest_MiD08.csv
        vencoPyOutput: vencoPyOutput
        flexPlotName: flexProfileComparison
#        inputDataDriveProfiles: inputProfiles_Drive_MiD08.csv
#        inputDataPlugProfiles: inputProfiles_Plug_MiD08.csv
    vencoPyOutput: vencoPyOutput
    aggPlotName: mobilityComparison
    flexPlotName: flexProfileComparison
    outputConfig: outputConfigREMix.yaml


labels:
<<<<<<< Updated upstream
    runLabel: masterBranch
    technologyLabel: bat50_cons20_pow11_
=======
    runLabel: phdSeminar
    technologyLabel: cons20_bat50_pow11_
>>>>>>> Stashed changes
    outputFileName: VencoPy_MR1_alpha1_batCap40_cons15
    strAdd:
