#-*- encoding:utf-8 -*-
# __version__ = '0.0.9'
# __maintainer__ = 'Niklas Wulff 2019-02-12'
# __contributors__ = 'Fabia Miorelli, Parth Butte'
# __email__ = 'Niklas.Wulff@dlr.de'
# __birthdate__ = '2019-02-12'
# __status__ = 'dev'  # options are: dev, test, prod

chargingInfrastructureDistributions:  # Probabilities given for each location aka trip purpose
    'DRIVING': False
    'HOME': True
    'WORK': False
    'SCHOOL': False
    'SHOPPING': False
    'LEISURE': False
    'OTHER': False
    'NA': False