Nodes:
  - 'Albania'
  - 'Algeria'
  - 'Austria'
  - 'Belgium'
  - 'Bosnia_Herzegovina'
  - 'Bulgaria'
  - 'Croatia'
  - 'Czech_Republic'
  - 'Estonia'
  - 'Finland'
  - 'France'
  - 'GermanyNorth_data'
  - 'GermanySouth_data'
  - 'Greece'
  - 'Hungary'
  - 'Ireland'
  - 'Italy'
  - 'Latvia'
  - 'Lithuania'
  - 'Luxembourg'
  - 'Macedonia'
  - 'Montenegro'
  - 'Morocco'
  - 'Netherlands'
  - 'Norway'
  - 'Poland'
  - 'Portugal'
  - 'Romania'
  - 'Serbia'
  - 'Slovakia'
  - 'Slovenia'
  - 'Spain'
  - 'Sweden'
  - 'Switzerland'
  - 'Tunisia'
  - 'UK'
  - 'Ukraine'

NonNullNodes:
  - 'GermanyNorth_data'
  - 'GermanySouth_data'