#-*- coding:utf-8 -*-

# __version__ = '0.0.9'
# __maintainer__ = 'Niklas Wulff 2019-02-12'
# __contributors__ = 'Fabia Miorelli, Parth Butte'
# __email__ = 'Niklas.Wulff@dlr.de'
# __birthdate__ = '2019-02-12'
# __status__ = 'dev'  # options are: dev, test, prod

# This config holds all relative paths and filenames for flexEstimators.py

inputDataScalars:

    MiD17:
        Minimum_daily_mileage: 0.0              #km
        Battery_capacity: 50.0                  #kWh
        Electric_consumption_NEFZ: 145.0        #kWh/100km
        Fuel_consumption_NEFZ: 1.0              #l/100km
        Electric_consumption_Artemis: 20.0      #kWh/100km
        Fuel_consumption_Artemis: 1.0           #l/100km
        Maximum_SOC: 0.97                       #%
        Minimum_SOC: 0.03                       #%
        Rated_power_of_charging_column: 11.0    #kW
        Is_BEV?: 1

    KiD: # differentiate between light commercial vehicle (LCV), medium-duty truck (MDT), and heavy-duty truck (HDT).
        Minimum_daily_mileage: 0.0              #km
        Battery_capacity: 500.0                 #kWh
        Electric_consumption_NEFZ: 140.0        #kWh/100km
        Fuel_consumption_NEFZ: 28.0             #l/100km
        Electric_consumption_Artemis: 140.0     #kWh/100km
        Fuel_consumption_Artemis: 28.0          #l/100km
        Maximum_SOC: 0.97                       #%
        Minimum_SOC: 0.03                       #%
        Rated_power_of_charging_column: 11.0    #kW
        Is_BEV?: 1

    MiD08:
        Minimum_daily_mileage: 0.0              #km
        Battery_capacity: 50.0                  #kWh
        Electric_consumption_NEFZ: 20.0         #kWh/100km
        Fuel_consumption_NEFZ: 1.0              #l/100km
        Electric_consumption_Artemis: 20.0      #kWh/100km
        Fuel_consumption_Artemis: 1.0           #l/100km
        Maximum_SOC: 0.97                       #%
        Minimum_SOC: 0.03                       #%
        Rated_power_of_charging_column: 11.0    #kW
        Is_BEV?: 1




