#-*- coding:utf-8 -*-

# __version__ = '0.1.X'
# __maintainer__ = 'Niklas Wulff'
# __contributors__ = 'Fabia Miorelli, Parth Butte'
# __email__ = 'niklas.wulff@dlr.de'
# __birthdate__ = '2019-02-12'
# __status__ = 'prod'  # options are: dev, test, prod

# This config holds all technical input assumptions and thresholds

Minimum_daily_mileage: 0.0 # in km, cut-off mileage to exclude profiles
Battery_capacity: 50 # in kWh, input assumption for battery capacity
Electric_consumption: 18.0 # in kWh/100km, input assumption for specific electric consumption
Fuel_consumption: 1.0 # in l/100km, input assumption for specific fuel consumption for auxiliary fuel
Electric_consumption_corr: 18.0 # in kWh/100km, assumption for potential correction after aggregation
Fuel_consumption_corr: 1.0 # in l/100km, assumption for potential correction after aggregation
Maximum_SOC: 0.97 # in %
Minimum_SOC: 0.03 # in %
Losses_charging: 1 # FIXME: Should be renamed to something like loss factor
Is_BEV?: 1 # 1=BEV, 0=PHEV (not yet tested)
SoC_plugging_threshold: 0.8

# For plugging choice implementation
# f(x) = 1 - 1 / (1 + exp(-k * (x - SOC))) with k being the slope at 50% probability and SOC being SOC at 50% probability
plugFunction:
    k: 15
    SOC: 1

BMMParams:
    weekdayPlugin:
        mode1:
            w1: 0.23
            a1: 32.8
            b1: 76.76
        mode2:
            w2: 0.14
            a1: 32.8
            b1: 33.4
        mode3:
            w3: 0.56
            a3: 4.13
            b3: 2.34
        mode4:
            w4: 0.08
            a4: 36.12
            b4: 42.65
