#-*- encoding:utf-8 -*-

# __version__ = '0.1.X'
# __maintainer__ = 'Niklas Wulff'
# __contributors__ = 'Fabia Miorelli, Parth Butte'
# __email__ = 'niklas.wulff@dlr.de'
# __birthdate__ = '2019-02-12'
# __status__ = 'prod'  # options are: dev, test, prod

# This config holds all configurations for gridModelers.py. The config already foreshadows next releases where
# probabilities will be given for each rated charging power at each parking purpose. In the beta release (0.1.X) only
# chargingInfrastructureMappings is used


chargingInfrastructureMappings:  # Simple grid model: Explicit mapping given for each location aka parking purpose
    'DRIVING': False
    'HOME': True
    'WORK': True
    'SCHOOL': False
    'SHOPPING': True
    'LEISURE': False
    'OTHER': False
    'NA': False
    # KiD additional purposes below
    'PEOPLE_MOBILITY': False
    'TRANSPORT': False
    'SERVICES': False

ratedPowerSimple: 11

# MOVE TO GRID MODELER TUTORIAL to show implementation of discrete mapping in probabilities
# gridAvailabilityProbability:  # Grid model 2: Probabilities given for each location aka trip purpose and capacity
##   PURPOSE:
##       POWER: PROBABILITY
#    'DRIVING':
#        0: 1
#    'HOME':
#        11: 1
#    'WORK':
#        11: 1
#    'SCHOOL':
#        0: 1
#    'SHOPPING':
#        0: 1
#    'LEISURE':
#        0: 1
#    'OTHER':
#        0: 1
#        1: 0

gridAvailabilityDistribution:  # Grid model 3: Probabilities given for each location aka trip purpose and capacity
    'DRIVING':
        0: 1
        #0.005: 75
        #0.005: 150
    'HOME':
        3.6 : 0.2
        11: 0.2            #0.25 (0.75 - 0.50) probability of finding a charging station
        22 : 0        #0.05 (0.80 - 0.75) probability of finding a charging station
        0: 0.6            #0.2 (1- 0.80) probability of finding a charging station
    'WORK':
        11 : 0.2
        22: 0.2
        0 : 0.6
    'SCHOOL':
        11: 0
        22: 0
        0: 1
    'SHOPPING':
        11: 0.2
        22: 0.2
        0: 0.6
    'LEISURE':
        11: 0.2
        22: 0.2
        0: 0.6
    'OTHER':
        11: 0.2
        22: 0.2
        0: 0.6
    '0.0':
        0: 1
